name: Publish

on:
  release:
    types: [created]

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check quality
        run: make quality

      - name: Run tests
        run: make test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1

      - name: Build the binary
        uses: skx/github-action-build@master
        env:
          RELEASE_VERSION: ${{ github.event.release.tag_name }}

      - name: Upload the binary
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: monorepo-diff-buildkite-plugin-linux
