name: Publish

on:
  push:
    branches:
      - master

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check quality
        run: make quality

      - name: Run tests
        run: make test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1

      - name: Build binary
        run: make build-linux

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Pre Release"
          files: monorepo-diff-buildkite-plugin-linux
