name: Publish

on:
  push:
    branches:
      - master

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check quality
        run: make quality

      - name: Run tests
        run: make test

      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash)

        # set RELEASE_VERSION  ${{ github.event.release.tag_name }}
        # release binary
        # update changelog
        # update readme version numbers
        # add contributors
